# -*- coding: utf-8 -*-
"""Parse docs/*.md chapters into src/data/chapters.generated.ts (verbatim transcription)."""
import json
import re
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
DOCS = ROOT.parent / "docs"
OUT = ROOT / "src" / "data" / "chapters.generated.ts"

FILES = [
    ("ch1", "第一章：琥珀之门的咆哮.md"),
    ("ch2", "第二章：通往符文山谷之路.md"),
    ("ch3", "第三章：先民宝库的暗涌.md"),
    ("interlude", "幕间：觅奇兽之月.md"),
    ("ch4", "第四章：暮光守望.md"),
    ("ch5", "第五章：先民宝库.md"),
    ("interlude2", "幕间：月光银之月.md"),
    ("ch6", "第六章：极乐洞穴.md"),
]


def parse(path: pathlib.Path):
    lines = path.read_text(encoding="utf-8").splitlines()
    title = lines[0].strip().lstrip("#").strip()

    end_idx = next(i for i, l in enumerate(lines) if "【" in l and "完】**" in l)
    end_mark = re.search(r"【(.+?)】", lines[end_idx]).group(1)

    body_lines = lines[1:end_idx]
    trailer = lines[end_idx + 1:]

    blocks = []
    for raw in body_lines:
        s = raw.strip()
        if not s:
            continue
        if s == "---":
            blocks.append({"kind": "hr", "text": ""})
        elif s.startswith("## "):
            blocks.append({"kind": "h2", "text": s[3:].strip()})
        else:
            blocks.append({"kind": "p", "text": s.rstrip()})

    poem, report = [], ""
    for raw in trailer:
        s = raw.strip()
        if not s:
            continue
        if s.startswith("_"):
            report = s.strip("_").strip()
        else:
            s = s.lstrip(">").strip().rstrip("  ").rstrip()
            if s:
                poem.append(s)

    return title, end_mark, blocks, poem, report


def j(x):
    return json.dumps(x, ensure_ascii=False)


out = [
    "// AUTO-GENERATED by scripts/gen-chapters.py — 正文逐字转录自 docs/，请勿手改。",
    "import type { ChapterBody } from './types'",
    "",
    "export const chapterBodies: Record<string, ChapterBody> = {",
]
report_counts = []
for cid, fname in FILES:
    title, end_mark, blocks, poem, report_text = parse(DOCS / fname)
    n_p = sum(1 for b in blocks if b["kind"] == "p")
    n_hr = sum(1 for b in blocks if b["kind"] == "hr")
    n_h2 = sum(1 for b in blocks if b["kind"] == "h2")
    # verification: non-empty source body lines (excl. title/endmark/poem/report)
    src_lines = (DOCS / fname).read_text(encoding="utf-8").splitlines()
    end_idx = next(i for i, l in enumerate(src_lines) if "【" in l and "完】**" in l)
    src_body_nonempty = sum(1 for l in src_lines[1:end_idx] if l.strip())
    ok = "OK" if src_body_nonempty == len(blocks) else "MISMATCH!"
    report_counts.append((fname, title, n_p, n_hr, n_h2, len(blocks), src_body_nonempty, ok, len(poem)))

    out.append(f"  {j(cid)}: {{")
    out.append(f"    title: {j(title)},")
    out.append(f"    endMark: {j('【' + end_mark + '】')},")
    out.append("    blocks: [")
    for b in blocks:
        out.append(f"      {{ kind: {j(b['kind'])}, text: {j(b['text'])} }},")
    out.append("    ],")
    out.append(f"    poem: [{', '.join(j(l) for l in poem)}],")
    out.append(f"    battleReport: {j(report_text)},")
    out.append("  },")
out.append("}")
out.append("")
OUT.write_text("\n".join(out), encoding="utf-8")

print(f"{'file':<28} {'title':<14} {'p':>4} {'hr':>3} {'h2':>3} {'blocks':>6} {'srcLines':>8} {'check':>9} {'poem':>4}")
for fname, title, n_p, n_hr, n_h2, nb, srcn, ok, np_ in report_counts:
    print(f"{fname:<28} {title:<14} {n_p:>4} {n_hr:>3} {n_h2:>3} {nb:>6} {srcn:>8} {ok:>9} {np_:>4}")
print("Wrote", OUT)
